// <auto-generated />
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(ChargingStationContext))]
    partial class ChargingStationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Model.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingPower")
                        .HasColumnType("integer");

                    b.Property<string>("ChargingValuesForEachDayAndHour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChargingStations");
                });

            modelBuilder.Entity("Dal.Model.SimulationInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalProbabilityMultiplier")
                        .HasColumnType("integer");

                    b.Property<int>("AverageConsumptionOfCars")
                        .HasColumnType("integer");

                    b.Property<string>("ChargingStations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SimulationInputs");
                });

            modelBuilder.Entity("Dal.Model.SimulationOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargingStationSimulationResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ConcurrencyFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfChargingEventsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfChargingEventsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfChargingEventsPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfChargingEventsPerYear")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEnergyCharged")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SimulationOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
